{{- $fullName := .Release.Name -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  annotations:
    kubernetes.io/ingress.class: test1
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/affinity: cookie
  labels:
    app: {{ template "blue-green.name" . }}
    chart: {{ template "blue-green.chart" . }}
    release: {{ .Release.Name }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ $fullName }}-service-prod
            servicePort: http
  - host: {{ .Values.ingress.stagehostname }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ $fullName }}-service-stage
            servicePort: http
